[package]
name = "gpuminer"
version.workspace = true
edition.workspace = true
build = "build.rs"

[[bin]]
name = "gpuminer"
path = "src/main.rs"

[features]
default = []
cuda = []

[dependencies]
sha2.workspace = true
sha3.workspace = true
hmac.workspace = true
k256.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
rand.workspace = true
anyhow.workspace = true
subtle.workspace = true
